name: Update Quote Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Quote Badge
        run: |
          QUOTES=("It’s dangerous to go alone! Take this." "Do a barrel roll!" "Finish him!")
          RANDOM_QUOTE=${QUOTES[$RANDOM % ${#QUOTES[@]}]}
          curl -o badge.svg "https://img.shields.io/badge/Glenn's%20Quote-$RANDOM_QUOTE-00FF00?style=for-the-badge"
          mkdir -p .github/badges
          mv badge.svg .github/badges/quote-badge.svg
      - name: Commit Badge
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .github/badges/quote-badge.svg
          git commit -m "Update daily quote badge" || echo "No changes to commit"
          git push
